### ISSUE TITLE
[Improvement] Length of passphrase

### ISSUE THREAD

**Issue by itsanogo** [legarspol/miniLock-android#2]
I'm very pleased with miniLock insisting on users using a long passphrase.

1. What wordlist is being used?

2. Could miniLock suggest a 10 words passphrase length instead of 7?

Cheers!

**Comment by legarspol** [comment]
Hello @itsanogo,

1. You can find the list of words in the source here:
https://github.com/legarspol/miniLock-android/blob/master/app/src/main/assets/word_catalog.txt
As this is a port of the original JS implementation, I reused the original list of words that you can find here: https://github.com/kaepora/miniLock/blob/master/src/js/lib/phrase.js#L44
2. There are no plans to change the number of words the password suggestion shows as I try to be as close as possible to the original implementation. Feel free to use a password with as many words as you like! Look for "password generator words" on your search engine and use any website like https://www.nexcess.net/web-tools/secure-password-generator/

**Comment by itsanogo** [comment]
All right, thank you!
Cheers
